<!DOCTYPE html>
<html lang="ja">
<head>
  <?php if (file_exists(__DIR__ . '/../ga.html')) include __DIR__ . '/../ga.html'; ?>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <title>モグポン！</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div id="screen-title" class="screen active">
    <h1 class="logo">モグポン！</h1>
    <div class="highscore-display">
      <span class="label">ハイスコア</span>
      <span id="title-highscore">0</span>
    </div>
    <button id="btn-start" class="btn-primary">スタート！</button>
    <p class="hint">キャラをタップして叩こう！<br>⏱ 30秒で何匹叩けるかな？</p>
  </div>

  <div id="screen-game" class="screen">
    <div class="game-header">
      <div class="stat-box">
        <span class="label">スコア</span>
        <span id="score">0</span>
      </div>
      <div class="stat-box timer-box">
        <span class="label">のこり</span>
        <span id="timer">30</span>
      </div>
      <div class="stat-box">
        <span class="label">ハイスコア</span>
        <span id="game-highscore">0</span>
      </div>
    </div>
    <div id="grid" class="grid">
      <!-- 9 holes generated by JS -->
    </div>
  </div>

  <div id="screen-result" class="screen">
    <div class="result-emoji" id="result-emoji">🎉</div>
    <h2 class="result-title">タイムアップ！</h2>
    <div class="result-card">
      <div class="result-row"><span>スコア</span><span id="result-score">0</span></div>
      <div class="result-row result-hs"><span>ハイスコア</span><span id="result-highscore">0</span></div>
    </div>
    <button id="btn-retry" class="btn-primary">もういちど！</button>
    <button id="btn-title" class="btn-secondary">タイトルへ</button>
  </div>

  <script src="js/sound.js"></script>
  <script src="js/game.js"></script>
  <script src="js/main.js"></script>
</body>
</html>
